config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/marketplace:
      branch: master
      repo: https://github.com/cyfronet-fid/marketplace.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sangria-binturong.sh
        container: qc.acc_muggy-turquoise-dragon
  QC.Doc:
    repos:
      github.com/cyfronet-fid/marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-purple-zebu.sh
        container: qc.doc_shaggy-aquamarine-dalmatian
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-firebrick-mist.sh
        container: qc.doc_chewy-buff-catfish
      github.com/cyfronet-fid/marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-amaranth-spoonbill.sh
        container: qc.doc_cheeky-amaranth-setter
  QC.Lic:
    repos:
      github.com/cyfronet-fid/marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-maroon-penguin.sh
        container: qc.lic_stinky-ochre-schnauzer
  QC.Met:
    repos:
      github.com/cyfronet-fid/marketplace cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-grey-tapir.sh
        container: qc.met_silly-puce-echidna
  QC.Sty:
    repos:
      github.com/cyfronet-fid/marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-scarlet-balinese.sh
        container: qc.sty_freaky-salmon-collie
      github.com/cyfronet-fid/marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-carmine-spaniel.sh
        container: qc.sty_squirrely-cobalt-booby
  QC.Ver:
    repos:
      github.com/cyfronet-fid/marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-mauve-sparrow.sh
        container: qc.ver_greasy-brass-toad
timeout: 5400
