config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/marketplace:
      branch: development
      repo: https://github.com/cyfronet-fid/marketplace.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.viridian_patient_clownfish.sh
        container: qc.acc_amethyst_artistic_flamingo
  QC.Doc:
    repos:
      github.com/cyfronet-fid/marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_dreamy_otter.sh
        container: qc.doc_espresso_skeptical_hedgehog
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.cerise_impulsive_cougar.sh
        container: qc.doc_thistle_courageous_hornbill
      github.com/cyfronet-fid/marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sage_zany_badger.sh
        container: qc.doc_paprika_apathetic_salamander
  QC.Lic:
    repos:
      github.com/cyfronet-fid/marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.red_diligent_gull.sh
        container: qc.lic_storm_eccentric_griffin
  QC.Met:
    repos:
      github.com/cyfronet-fid/marketplace cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.kiwi_persistent_jackal.sh
        container: qc.met_rust_gracious_dhole
  QC.Sty:
    repos:
      github.com/cyfronet-fid/marketplace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.peach_amiable_hamster.sh
        container: qc.sty_prussian_rustic_okapi
      github.com/cyfronet-fid/marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.marina_vigilant_stingray.sh
        container: qc.sty_butter_relaxed_alpaca
      github.com/cyfronet-fid/marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.thistle_hopeful_moth.sh
        container: qc.sty_cayenne_thoughtful_phoenix
  QC.Ver:
    repos:
      github.com/cyfronet-fid/marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blush_passionate_impala.sh
        container: qc.ver_marigold_warm_antelope
timeout: 5400
