config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/marketplace:
      branch: development
      repo: https://github.com/cyfronet-fid/marketplace.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-chocolate-dormouse.sh
        container: qc.acc_queasy-russet-clam
  QC.Doc:
    repos:
      github.com/cyfronet-fid/marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-indigo-dachshund.sh
        container: qc.doc_stuffy-cream-warthog
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-celadon-eagle.sh
        container: qc.doc_pokey-dandelion-sponge
      github.com/cyfronet-fid/marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cream-vulture.sh
        container: qc.doc_gloppy-charcoal-hyrax
  QC.Lic:
    repos:
      github.com/cyfronet-fid/marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-azure-robin.sh
        container: qc.lic_squirrely-cinnamon-rat
  QC.Met:
    repos:
      github.com/cyfronet-fid/marketplace cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magnolia-harrier.sh
        container: qc.met_cozy-tangerine-discus
  QC.Sty:
    repos:
      github.com/cyfronet-fid/marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-burgundy-newt.sh
        container: qc.sty_blurry-green-chin
      github.com/cyfronet-fid/marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-ultramarine-bandicoot.sh
        container: qc.sty_messy-yellow-paradise
  QC.Ver:
    repos:
      github.com/cyfronet-fid/marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-red-swan.sh
        container: qc.ver_gloppy-magnolia-eleuth
timeout: 5400
