config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/marketplace:
      branch: master
      repo: https://github.com/cyfronet-fid/marketplace.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-razzmatazz-fish.sh
        container: qc.acc_pretty-cinnabar-cattle
  QC.Doc:
    repos:
      github.com/cyfronet-fid/marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-lavender-barb.sh
        container: qc.doc_leaky-asparagus-zebra
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-tangerine-squirrel.sh
        container: qc.doc_breezy-periwinkle-bear
      github.com/cyfronet-fid/marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-chartreuse-emu.sh
        container: qc.doc_queasy-bistre-pinscher
  QC.Lic:
    repos:
      github.com/cyfronet-fid/marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-sepia-serval.sh
        container: qc.lic_flaky-peach-spoonbill
  QC.Met:
    repos:
      github.com/cyfronet-fid/marketplace cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-maroon-cow.sh
        container: qc.met_frumpy-brass-scorpion
  QC.Sty:
    repos:
      github.com/cyfronet-fid/marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-ruby-oriole.sh
        container: qc.sty_sleazy-amber-okapi
      github.com/cyfronet-fid/marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.surly-linen-heron.sh
        container: qc.sty_randy-malachite-fowl
  QC.Ver:
    repos:
      github.com/cyfronet-fid/marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-myrtle-kangaroo.sh
        container: qc.ver_breezy-plum-robin
timeout: 5400
